services:
  plex-discord-bot:
    container_name: plex-discord-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: sh /app/start.sh
    ports:
      - "10000:10000"  # Webhook port
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env
      - ./start.sh:/app/start.sh
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
