services:
  plex-discord-bot:
    container_name: plex-discord-bot
    image: ghcr.io/cellwebb/discord-plex-announcer:latest
    restart: unless-stopped
    ports:
      - "10000:10000"  # Webhook port
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_MOVIE_CHANNEL_ID=${DISCORD_MOVIE_CHANNEL_ID}
      - DISCORD_NEW_SHOWS_CHANNEL_ID=${DISCORD_NEW_SHOWS_CHANNEL_ID}
      - DISCORD_RECENT_EPISODES_CHANNEL_ID=${DISCORD_RECENT_EPISODES_CHANNEL_ID}
      - DISCORD_BOT_DEBUG_CHANNEL_ID=${DISCORD_BOT_DEBUG_CHANNEL_ID}
      - PLEX_BASE_URL=${PLEX_BASE_URL}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - MOVIE_LIBRARY=${MOVIE_LIBRARY:-Movies}
      - TV_LIBRARY=${TV_LIBRARY:-TV Shows}
      - NOTIFY_MOVIES=${NOTIFY_MOVIES:-true}
      - NOTIFY_NEW_SHOWS=${NOTIFY_NEW_SHOWS:-true}
      - NOTIFY_RECENT_EPISODES=${NOTIFY_RECENT_EPISODES:-true}
      - RECENT_EPISODE_DAYS=${RECENT_EPISODE_DAYS:-30}
      - CHECK_INTERVAL=${CHECK_INTERVAL:-3600}
      - PLEX_CONNECT_RETRY=${PLEX_CONNECT_RETRY:-3}
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}
      - WEBHOOK_ENABLED=${WEBHOOK_ENABLED:-true}
      - WEBHOOK_HOST=${WEBHOOK_HOST:-0.0.0.0}
      - WEBHOOK_PORT=${WEBHOOK_PORT:-10000}
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    network_mode: host
