services:
  plex-discord-bot:
    container_name: plex-discord-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/app
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - PLEX_URL=${PLEX_URL}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - MOVIE_LIBRARY=${MOVIE_LIBRARY}
      - TV_LIBRARY=${TV_LIBRARY}
      - NOTIFY_MOVIES=${NOTIFY_MOVIES}
      - NOTIFY_TV=${NOTIFY_TV}
      - CHECK_INTERVAL=${CHECK_INTERVAL}
      - DATA_FILE=${DATA_FILE}
      - TV_SHOW_BUFFER_FILE=${TV_SHOW_BUFFER_FILE:-tv_show_buffer.json}
      - TV_BUFFER_TIME=${TV_BUFFER_TIME:-7200}
      - PLEX_CONNECT_RETRY=${PLEX_CONNECT_RETRY:-3}
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}
    healthcheck:
      test: ["CMD", "python", "-c", "import os, sys; sys.exit(0 if os.path.exists('/app/plex_discord_bot.log') else 1)"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
